### ISSUE TITLE
求助，谢谢了

### ISSUE THREAD

**Issue by 120660021** [chentao0707/QrCodeScan#10]
使用你的ZBarLib打包出现
Errors occurred during the build.
Errors running builder 'Integrated External Tool Builder' on project 'ZBarLib'.
The file does not exist for the external tool named ZBarLib.
The file does not exist for the external tool named ZBarLib.

**Comment by 120660021** [comment]
马上就要上线了 ，出现这个问题 ，希望大神能给予帮助

**Comment by chentao0707** [comment]
错误信息不全，看不出问题

**Comment by 120660021** [comment]
我直接使用的你的
![image](https://cloud.githubusercontent.com/assets/8433054/7495771/94d10bbc-f442-11e4-8cdd-5803074c7072.png)

运行没有问题  

打包的时候出现
![Uploading image.png…]()

**Comment by chentao0707** [comment]
ZBarLib 是一个NDK编译so文件的项目，你为什么用这个打包apk？？还是我的理解有误？

**Comment by 120660021** [comment]
那我需要怎么做？对于jni我不是很了解

**Comment by 120660021** [comment]
我只是把ZBarLib当成library导入  ，然后打包

**Comment by 120660021** [comment]
能加你QQ请教吗   ？  我的QQ120660021   万分感谢

**Comment by 120660021** [comment]
注意：如果是想要在自己的项目中直接使用项目提供的ZbarManager源码。需要保持包名一致（com.zbar.lib）   这是你写得说明。因为我的工程名和com.zbar.lib不一样，使用你编译的libzbar.so不行，所以我才用ZBarLib当成library导入到我的工程，运行是没有问题，但是打不了包，求助，这问题困扰2天了、

**Comment by chentao0707** [comment]
你可以将ZBarManager做成jar包使用，不然只能重新编译so文件，zbarlib项目和二维码扫描不相关，不是library项目，只是用来生成so文件的，还有问题加我qq

**Comment by 120660021** [comment]
你QQ是多少？

**Comment by chentao0707** [comment]
我的github首页就有

**Comment by 120660021** [comment]
非常感谢大神热情帮助，已经成功解决问题
