### ISSUE TITLE
64位系统支持

### ISSUE THREAD

**Issue by yangjiannan2018** [chentao0707/QrCodeScan#11]
请问要64位系统支持，怎么编译呢，谢谢！

**Comment by chentao0707** [comment]
已经支持了64位的，请移步 https://github.com/SkillCollege/ZBarAndroidSDK

**Comment by yangjiannan2018** [comment]
能在QrCodeScan 这个项目编译64位的so 库吗 ？ 谢谢！

**Comment by chentao0707** [comment]
也是可以的。ZBarLib就是ndk源码，你只需要升级你本地的ndk-bulid版本就可以输出64位so库了

**Comment by yangjiannan2018** [comment]
谢谢，已经编译出了。
