### ISSUE TITLE
这个写错了吧。。。

### ISSUE THREAD

**Issue by mahuidong** [chentao0707/QrCodeScan#12]
基于以上一些原因，笔者决定何不将二者结合起来，用ZXing来控制摄像头取得图像，用ZBar来解析扫描到的数据，最终形成目前的项目。

用zbar取图，zxing解析数据 吧

**Comment by chentao0707** [comment]
可能我表述的有问题，是ZXing里面的Camera控制代码获取图像。ZBar提供的解码方法解析数据

**Comment by cxbiao** [comment]
Zbar或者ZXing扫描相册中的二维码图片几乎都扫不出来，楼主有解决方案吗？
