### ISSUE TITLE
支持arm64吗？

### ISSUE THREAD

**Issue by kingJ430** [chentao0707/QrCodeScan#15]
现在使用发现arm64位的机型奔溃，现在so不支持arm64吗

**Comment by GISirFive** [comment]
我也遇到同样的问题，在64位机型上崩溃

**Comment by Carrie-L** [comment]
64位so编译成功，http://blog.csdn.net/xingliuyang/article/details/46710345 其实只要下载最新版的ndk就可以了，APP_ABI := all

**Comment by zhugecunfu** [comment]
亲，能把64位的so共享出来吗，项目紧，急求，感激！

150504634@qq.com

**Comment by nashxk** [comment]
有没有可以Android Studio编译so文件的教程？谢谢。

**Comment by chentao0707** [comment]
项目里面有jni的源码，可以自己下载build就可以了，什么平台的so都可以导出
