### ISSUE TITLE
arm64-v8a报错

### ISSUE THREAD

**Issue by jayzqj** [chentao0707/QrCodeScan#18]
如果项目中的lib下面有arm64-v8a目录的话，同时你的Android手机是arm64架构的，就会报错。
说找不到.so文件。所以使用这个，项目中的libs目录中不能有arm64目录

**Comment by chentao0707** [comment]
试试只放armeabi目录

**Comment by jayzqj** [comment]
只放armeabi目录是可以的，但是项目中有很多其它的.so库，他们建了arm64这个目录。这种情况就悲催了

**Comment by chentao0707** [comment]
那就需要重新编译生成了，你可以下载编译的源码，生成arm64的so

**Comment by chentao0707** [comment]
如果不编译，尝试使用splits裁剪一下so的目录
