### ISSUE TITLE
Android Studio 下报错

### ISSUE THREAD

**Issue by Houny** [chentao0707/QrCodeScan#2]
作者您好，我尝试使用您提供的代码。把它跑在Android Studio上，但是它没法引入那个包，
 Couldn't load libzbar from loader dalvik.system.PathClassLoader   findLibrary returned null
这是什么问题，该怎么解决呢？

**Comment by Houny** [comment]
已经知道问题所在了，我写下来供使用Android Studio 的朋友参考
1.把so文件放到如下目录(src/main/jniLibs/armeabi/libzbar.so)
|src
|--main/
|----java/
|----res/
|----jniLibs/
|------armeabi
|--------libzbar.so
2.Rebuild Project
注意：如果是想要在自己的项目中直接使用作者提供的Activity源码。需要保持包名不变。若要使用so包中方法，需要保持包名和作者的包名一直，只需要调用的那个java文件的包名一致就可以，不需要整个项目都一直。

**Comment by chentao0707** [comment]
谢谢你的测试。。。至于包名一致，这个是jni方面的要求，另外如果需要放到其他包中，jni的源码也已经提供，可以自行修改的。

**Comment by Gisonrg** [comment]
@Houny 你好，我正在学习安卓开发，请问能告诉我怎么在AndroidStudio中import这个包吗？我导入后总是无法成功运行，谢谢！

**Comment by hxors** [comment]
在build.gradle中的android{}部分，添加如下代码，把.so文件放在libs目录下即可。
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
